import { mean, variance, descriptiveSummary, welchTTest, studentTTest, oneWayAnova, twoWayAnova, pairedTTest, wilcoxonSignedRank, mannWhitney, kruskalWallis, friedmanTest, chiSquareTest, fisherExactTest, kaplanMeier, logRankTest, pearsonCorrelation, spearmanCorrelation, linearRegression, pairwiseWelch } from './src/core/stats.js';
import { parseDelimited, toCsv } from './src/core/csv.js';
import { createProject, parseProject, serializeProject } from './src/core/project.js';
import { recommendAnalyses } from './src/core/guidance.js';
import { PLOT_TYPES, createFigure, validateFigure } from './src/core/figure.js';
import { renderGroupedSvg, renderLayoutSvg, renderXYSvg, renderSurvivalSvg, renderHeatmapSvg, renderCorrelationMatrixSvg, renderResidualSvg, renderQqSvg, renderEcdfSvg, renderBlandAltmanSvg } from './src/core/renderer.js';
import { filterRows, transformNumericColumn, detectTableMode, inferAnalysisRoles } from './src/core/table.js';
import { createAnalysisRecord, addAnalysisRecord } from './src/core/analysis.js';
import { methodsSummary } from './src/core/methods.js';
import { applyFigureTemplate } from './src/core/templates.js';
import { encodeRgbTiff } from './src/core/tiff.js';
import { reorderPanels, updatePanel } from './src/core/panels.js';
import { analysisReadiness } from './src/core/validation.js';
import * as XLSX from 'xlsx';

const initialData = [['Control',92],['Control',88],['Control',95],['Control',90],['Control',87],['Control',93],['Treatment',70],['Treatment',74],['Treatment',69],['Treatment',76],['Treatment',72],['Treatment',68]];
let data = JSON.parse(localStorage.getItem('statista-data') || 'null') || initialData.map(([group, value]) => ({group, value}));
let currentAnalysis = 'welch';
let figure = createFigure(JSON.parse(localStorage.getItem('statista-figure') || 'null') || {});
let tableFilter = '';
let tableMode = localStorage.getItem('statista-table-mode') || 'column';
let roleKeys = JSON.parse(localStorage.getItem('statista-role-keys') || 'null') || {group:'group',value:'value'};
let multipleComparison = localStorage.getItem('statista-multiple-comparison') || 'Holm';
let analysisHistory = JSON.parse(localStorage.getItem('statista-analysis-history') || '[]');
let figureLibrary = JSON.parse(localStorage.getItem('statista-figure-library') || '[]');
let lastResult = null;
const undoStack = [], redoStack = [];
const $ = id => document.getElementById(id);
const groups = () => [...new Set(data.map(d => d[roleKeys.group]).filter(Boolean))];
const numbers = group => data.filter(d => d[roleKeys.group] === group).map(d => Number(d[roleKeys.value])).filter(Number.isFinite);
const numericColumns = () => [...new Set(data.flatMap(row => Object.keys(row)))].filter(key => key !== 'group' && data.filter(row => Number.isFinite(Number(row[key]))).length >= 3);
const formatNumber = value => Number.isFinite(value) ? value.toFixed(1) : '—';
function renderResultDetails(entries=[]){const target=$('results-detail');if(!target)return;target.innerHTML=entries.length?`<div class="detail-grid">${entries.map(([label,value])=>`<div><span class="eyebrow">${label}</span><strong>${value}</strong></div>`).join('')}</div>`:'';}
function recordAnalysis(){if(!lastResult)return;const record=createAnalysisRecord({method:lastResult.method,result:lastResult,tableMode,sourceRows:data.length,spec:{method:currentAnalysis,roles:roleKeys,variables:{group:roleKeys.group,outcome:roleKeys.value,x:figure.xKey||null,y:figure.yKey||null},figureType:figure.type,exclusions:{missingOutcome:data.filter(row=>!Number.isFinite(Number(row[roleKeys.value]))).length},multipleComparison}});analysisHistory=addAnalysisRecord(analysisHistory,record);localStorage.setItem('statista-analysis-history',JSON.stringify(analysisHistory));const count=$('history-count');if(count)count.textContent=`${analysisHistory.length} saved`;toast('Analysis saved to local history');}
function currentMethods(){return methodsSummary({method:currentAnalysis,result:lastResult||{},groups:groups(),xKey:numericColumns()[0],yKey:numericColumns()[1],correction:multipleComparison});}
function snapshot(){return JSON.stringify({data,figure,figureLibrary,tableMode,currentAnalysis,roleKeys,multipleComparison});}
function updateHistoryButtons(){const undo=$('undo');const redo=$('redo');if(undo)undo.disabled=!undoStack.length;if(redo)redo.disabled=!redoStack.length;}
function checkpoint(){undoStack.push(snapshot());if(undoStack.length>50)undoStack.shift();redoStack.length=0;updateHistoryButtons();}
function restore(serialized){const state=JSON.parse(serialized);data=state.data;figure=createFigure(state.figure);figureLibrary=Array.isArray(state.figureLibrary)?state.figureLibrary:figureLibrary;tableMode=state.tableMode||'column';currentAnalysis=state.currentAnalysis||'welch';roleKeys=state.roleKeys||{group:'group',value:'value'};multipleComparison=state.multipleComparison||'Holm';localStorage.setItem('statista-role-keys',JSON.stringify(roleKeys));localStorage.setItem('statista-multiple-comparison',multipleComparison);localStorage.setItem('statista-figure-library',JSON.stringify(figureLibrary));$('table-mode').value=tableMode;$('analysis-method').value=currentAnalysis;if($('multiple-comparison'))$('multiple-comparison').value=multipleComparison;updateHistoryButtons();refresh();syncFigureControls();renderFigureLibrary();}
function undo(){if(!undoStack.length)return;redoStack.push(snapshot());restore(undoStack.pop());toast('Undid last change');}
function redo(){if(!redoStack.length)return;undoStack.push(snapshot());restore(redoStack.pop());toast('Redid change');}

function renderTable() {
  const table = $('data-table');
  const columns = [...new Set(data.flatMap(row => Object.keys(row)))];
  if (!columns.includes('group')) columns.unshift('group'); if (!columns.includes('value')) columns.push('value');
  const heading = columns.map(column => `<th contenteditable="true" data-column="${column}">${column === 'value' ? 'Value (%)' : column}</th>`).join('');
  const visible = filterRows(data, tableFilter).map(row => ({row, index: data.indexOf(row)}));
  table.innerHTML = `<thead><tr>${heading}<th></th></tr></thead><tbody>` + visible.map(({row, index}) => `<tr>${columns.map(column => `<td contenteditable="true" data-i="${index}" data-k="${column}">${row[column] ?? ''}</td>`).join('')}<td><button class="text-button remove" data-i="${index}">×</button></td></tr>`).join('') + '</tbody>';
  table.querySelectorAll('[contenteditable]').forEach(cell => cell.addEventListener('focus', () => checkpoint(), {once:true}));
  table.querySelectorAll('[contenteditable]').forEach(cell => cell.addEventListener('input', event => {
    if (event.target.dataset.column) return;
    const i = Number(event.target.dataset.i), key = event.target.dataset.k, raw = event.target.innerText.trim();
    data[i][key] = key === 'value' || typeof data[i][key] === 'number' ? (raw === '' ? null : parseFloat(raw)) : raw;
    persistAndRenderDerived();
  }));
  table.querySelectorAll('th[contenteditable]').forEach(cell => cell.addEventListener('blur', event => { const oldKey = event.target.dataset.column, newKey = event.target.innerText.trim().toLowerCase().replace(/\s+/g, '_'); if (!newKey || newKey === oldKey || columns.includes(newKey)) { event.target.innerText = oldKey === 'value' ? 'Value (%)' : oldKey; return; } checkpoint(); data.forEach(row => { row[newKey] = row[oldKey]; delete row[oldKey]; }); if (roleKeys.group === oldKey) roleKeys.group = newKey; if (roleKeys.value === oldKey) roleKeys.value = newKey; localStorage.setItem('statista-role-keys', JSON.stringify(roleKeys)); refresh(); toast(`Renamed ${oldKey} to ${newKey}`); }));
  table.querySelectorAll('.remove').forEach(button => button.onclick = () => { checkpoint(); data.splice(Number(button.dataset.i), 1); refresh(); });
  table.addEventListener('paste', event => { const target = event.target.closest('td'); if (!target) return; event.preventDefault(); const pasted = event.clipboardData.getData('text/plain'), parsed = parseDelimited(pasted, '\t'); if (!parsed.rows.length) return; checkpoint(); const startRow = Number(target.dataset.i), startColumn = columns.indexOf(target.dataset.k); parsed.rows.forEach((row, r) => { if (!data[startRow+r]) data[startRow+r] = {}; row.forEach((value, c) => { const key = columns[startColumn+c] || `Column ${startColumn+c+1}`; if (!columns.includes(key)) columns.push(key); data[startRow+r][key] = key === 'value' ? parseFloat(value) : value; }); }); refresh(); toast(`Pasted ${parsed.rows.length} row${parsed.rows.length === 1 ? '' : 's'}`); });
  updateRoleControls(columns);
}
function updateRoleControls(columns=[...new Set(data.flatMap(row=>Object.keys(row)))]){const group=$('group-role'),value=$('value-role');if(!group||!value)return;group.innerHTML=columns.map(key=>`<option value="${key}">${key}</option>`).join('');value.innerHTML=columns.filter(key=>data.some(row=>Number.isFinite(Number(row[key])))).map(key=>`<option value="${key}">${key}</option>`).join('');if(columns.includes(roleKeys.group))group.value=roleKeys.group;if(columns.includes(roleKeys.value))value.value=roleKeys.value;}
function renderPanelControls(){const target=$('panel-controls');if(!target)return;const choices=[...supportedPlotTypes].map(id=>{const item=PLOT_TYPES.find(([key])=>key===id);return item?`<option value="${id}">${item[1]}</option>`:''}).join('');target.innerHTML=figure.panels.map((panel,index)=>`<div class="panel-control"><span>${index+1}</span><input data-panel-title="${index}" value="${panel.title||`Panel ${index+1}`}" aria-label="Panel ${index+1} title"/><select data-panel-type="${index}" aria-label="Panel ${index+1} type">${choices}</select><button class="text-button" data-panel-up="${index}" ${index?'':'disabled'}>↑</button><button class="text-button" data-panel-down="${index}" ${index<figure.panels.length-1?'':'disabled'}>↓</button></div>`).join('');target.querySelectorAll('[data-panel-title]').forEach(input=>input.oninput=event=>{checkpoint();figure.panels=updatePanel(figure.panels,indexOf(event.target,'panelTitle'),{title:event.target.value});persistAndRenderDerived()});target.querySelectorAll('[data-panel-type]').forEach(select=>select.onchange=event=>{checkpoint();figure.panels=updatePanel(figure.panels,indexOf(event.target,'panelType'),{type:event.target.value});persistAndRenderDerived()});target.querySelectorAll('[data-panel-up]').forEach(button=>button.onclick=event=>movePanel(Number(event.target.dataset.panelUp),-1));target.querySelectorAll('[data-panel-down]').forEach(button=>button.onclick=event=>movePanel(Number(event.target.dataset.panelDown),1));figure.panels.forEach((panel,index)=>{const select=target.querySelector(`[data-panel-type="${index}"]`);if(select)select.value=panel.type})}
function renderFigureLibrary(){const target=$('figure-library');if(!target)return;target.innerHTML=figureLibrary.length?figureLibrary.map((saved,index)=>`<div class="saved-figure"><button class="text-button" data-load-figure="${index}">${saved.title||`Figure ${index+1}`}</button><span>${saved.type||'dot'}</span><button class="text-button" data-delete-figure="${index}" aria-label="Delete saved figure">×</button></div>`).join(''):'<span class="format-note">No saved figures yet.</span>';target.querySelectorAll('[data-load-figure]').forEach(button=>button.onclick=()=>{checkpoint();figure=createFigure(figureLibrary[Number(button.dataset.loadFigure)]);persistAndRenderDerived();syncFigureControls();toast(`Loaded ${figure.title}`)});target.querySelectorAll('[data-delete-figure]').forEach(button=>button.onclick=()=>{checkpoint();figureLibrary.splice(Number(button.dataset.deleteFigure),1);localStorage.setItem('statista-figure-library',JSON.stringify(figureLibrary));renderFigureLibrary();toast('Figure removed from library')})}
function syncFigureControls(){if($('figure-title'))$('figure-title').value=figure.title;if($('figure-color-a'))$('figure-color-a').value=figure.colors[0];if($('figure-color-b'))$('figure-color-b').value=figure.colors[1];if($('figure-x-label'))$('figure-x-label').value=figure.xLabel;if($('figure-y-label'))$('figure-y-label').value=figure.yLabel;if($('figure-show-mean'))$('figure-show-mean').checked=figure.showMean;if($('figure-point-size'))$('figure-point-size').value=figure.pointSize;if($('figure-stroke-width'))$('figure-stroke-width').value=figure.strokeWidth;if($('figure-y-min'))$('figure-y-min').value=Number.isFinite(figure.yMin)?figure.yMin:'';if($('figure-y-max'))$('figure-y-max').value=Number.isFinite(figure.yMax)?figure.yMax:'';if($('chart-type'))$('chart-type').value=figure.type;renderPanelControls();renderAnnotationList();}
function indexOf(element,attribute){return Number(element.dataset[attribute]);}
function movePanel(index,direction){const destination=index+direction;if(destination<0||destination>=figure.panels.length)return;checkpoint();figure.panels=reorderPanels(figure.panels,index,destination);renderPanelControls();persistAndRenderDerived();}
function renderStats() {
  $('stats-table').innerHTML = '<div class="stats-row"><span>Group</span><span>n</span><span>Mean</span><span>Median</span><span>SD</span><span>SEM</span><span>95% CI</span></div>' + groups().map(group => { const summary = descriptiveSummary(numbers(group)), ci = summary.confidenceInterval95.every(Number.isFinite) ? `${formatNumber(summary.confidenceInterval95[0])}–${formatNumber(summary.confidenceInterval95[1])}` : '—'; return `<div class="stats-row"><span>${group}</span><span>${summary.n}</span><span>${formatNumber(summary.mean)}</span><span>${formatNumber(summary.median)}</span><span>${formatNumber(summary.sd)}</span><span>${formatNumber(summary.sem)}</span><span>${ci}</span></div>`; }).join('');
}
function renderChart() {
  const svg = $('chart'), gs = groups(), colors = figure.colors, values = data.map(d => d.value).filter(Number.isFinite);
  const min = Math.min(...values, 0), max = Math.max(...values, 100), scale = value => 300 - (value - min) / (max - min) * 245;
  let output = '';
  [0,.25,.5,.75,1].forEach(t => { const y = 55 + t * 245, value = max - t * (max - min); output += `<line x1="60" x2="590" y1="${y}" y2="${y}" class="chart-axis"/><text x="48" y="${y+4}" text-anchor="end" class="chart-label">${value.toFixed(0)}</text>`; });
  gs.forEach((group, groupIndex) => { const x = 170 + groupIndex * 260; output += `<text x="${x}" y="322" text-anchor="middle" class="chart-label">${group}</text>`; const a = numbers(group); a.forEach((value, i) => { const jitter = ((i * 37) % 50) - 25; output += `<circle cx="${x+jitter}" cy="${scale(value)}" r="5" fill="${colors[groupIndex % colors.length]}" fill-opacity=".85"/>`; }); if (figure.type === 'bar' && a.length) { const y = scale(mean(a)); output += `<line x1="${x-32}" x2="${x+32}" y1="${y}" y2="${y}" stroke="#17242a" stroke-width="3"/>`; } });
  svg.innerHTML = output;
}
function renderAnalysis() {
  const gs = groups(), availableNumerics = numericColumns(), suggestions = recommendAnalyses({groups: gs, paired: tableMode === 'multiple' || tableMode === 'xy', hasX: availableNumerics.length >= 2, hasSurvival: availableNumerics.some(key => /time|duration|days|follow/i.test(key))}), readiness = analysisReadiness(data, roleKeys), qualityNote = readiness.warnings.slice(0, 2).join(' ');
  $('recommendation').textContent = [`Suggested: ${suggestions[0].name} — ${suggestions[0].reason}`, qualityNote].filter(Boolean).join(' · ');
  const statusTag = document.querySelector('.analysis-panel .tag');
  if (statusTag) { statusTag.textContent = qualityNote ? 'Review data' : 'Ready'; statusTag.classList.toggle('success', !qualityNote); statusTag.classList.toggle('warning', Boolean(qualityNote)); }
  if (currentAnalysis === 'spearman') {
    const columns = numericColumns(), xKey = columns[0], yKey = columns[1];
    if (!xKey || !yKey) { $('analysis-title').textContent = 'Add two numeric columns'; $('significance').textContent = 'Spearman correlation needs two paired numeric variables'; return; }
    const pairs = data.map(row => [Number(row[xKey]), Number(row[yKey])]).filter(pair => pair.every(Number.isFinite)), x = pairs.map(pair => pair[0]), y = pairs.map(pair => pair[1]);
    try { const result = spearmanCorrelation(x, y); $('analysis-eyebrow').textContent = 'Analysis · Spearman rank correlation'; $('analysis-title').textContent = `${xKey} vs ${yKey}`; $('metric-one-label').textContent = 'Spearman ρ'; $('difference').textContent = result.rho.toFixed(3); $('metric-one-note').textContent = `${result.n} paired observations`; $('metric-two-label').textContent = 'Test statistic'; $('ci').textContent = result.t.toFixed(2); $('metric-two-note').textContent = `df = ${result.df}`; $('p-value').textContent = result.pValue < .001 ? '< 0.001' : result.pValue.toFixed(3); $('significance').textContent = result.pValue < .05 ? 'Evidence of a monotonic relationship' : 'No strong evidence of a monotonic relationship'; $('assumption-text').textContent = 'Paired numeric rows · rank-based monotonic association · inspect the scatterplot for influential observations.'; lastResult = result; renderResultDetails([['Method',result.method],['N',result.n],['Spearman ρ',result.rho.toFixed(4)],['t statistic',result.t.toFixed(3)],['Degrees of freedom',result.df],['P value',result.pValue.toFixed(4)]]); } catch (error) { $('significance').textContent = error.message; } return;
  }
  if (['correlation','regression'].includes(currentAnalysis)) {
    const columns = numericColumns(), xKey = columns[0], yKey = columns[1];
    if (!xKey || !yKey) { $('analysis-title').textContent = 'Add two numeric columns'; $('significance').textContent = 'This analysis needs two numeric variables with at least three paired rows'; return; }
    const pairs = data.map(row => [Number(row[xKey]), Number(row[yKey])]).filter(pair => pair.every(Number.isFinite)), x = pairs.map(pair => pair[0]), y = pairs.map(pair => pair[1]);
    try { const result = currentAnalysis === 'correlation' ? pearsonCorrelation(x, y) : linearRegression(x, y); $('analysis-eyebrow').textContent = `Analysis · ${result.method}`; $('analysis-title').textContent = `${xKey} vs ${yKey}`; $('metric-one-label').textContent = currentAnalysis === 'correlation' ? 'Pearson r' : 'Slope'; $('difference').textContent = currentAnalysis === 'correlation' ? result.r.toFixed(3) : result.slope.toFixed(3); $('metric-one-note').textContent = `${result.n} paired observations`; $('metric-two-label').textContent = currentAnalysis === 'correlation' ? 'Test statistic' : 'R²'; $('ci').textContent = currentAnalysis === 'correlation' ? result.t.toFixed(2) : result.r2.toFixed(3); $('metric-two-note').textContent = currentAnalysis === 'correlation' ? `df = ${result.df}` : `intercept ${result.intercept.toFixed(2)}`; $('p-value').textContent = result.pValue < .001 ? '< 0.001' : result.pValue.toFixed(3); $('significance').textContent = result.pValue < .05 ? 'Evidence of a relationship' : 'No strong evidence of a relationship'; $('assumption-text').textContent = 'Paired numeric rows · inspect scatterplot and residuals before interpretation. Correlation does not imply causation.'; lastResult=result; renderResultDetails([['Method',result.method],['N',result.n],['Estimate',currentAnalysis === 'correlation' ? result.r.toFixed(4) : result.slope.toFixed(4)],['Test statistic',result.t.toFixed(3)],['P value',result.pValue.toFixed(4)],...(currentAnalysis === 'regression' ? [['RMSE',result.rmse.toFixed(4)],['Residual SE',result.residualStandardError.toFixed(4)]] : [])]); } catch (error) { $('significance').textContent = error.message; }
    return;
  }
  if (currentAnalysis === 'survival') {
    const columns = numericColumns(), timeKey = columns.find(key => /time|duration|days|follow/i.test(key)) || columns[0], eventKey = columns.find(key => key !== timeKey && /event|status|censor|dead|outcome/i.test(key)) || columns.find(key => key !== timeKey && new Set(data.map(row => row[key]).filter(value => value != null).map(String)).size <= 2);
    if (!timeKey || !eventKey || gs.length !== 2) { $('analysis-title').textContent = 'Set up two-group survival data'; $('significance').textContent = 'Need two groups, a time/duration column, and a binary event/status column'; return; }
    const split = group => data.filter(row => String(row.group) === String(group)), a = split(gs[0]), b = split(gs[1]), timesA = a.map(row => row[timeKey]), timesB = b.map(row => row[timeKey]), eventsA = a.map(row => row[eventKey]), eventsB = b.map(row => row[eventKey]);
    try { const kmA = kaplanMeier(timesA, eventsA), kmB = kaplanMeier(timesB, eventsB), result = logRankTest(timesA, eventsA, timesB, eventsB); $('analysis-eyebrow').textContent = 'Analysis · Log-rank test'; $('analysis-title').textContent = `${gs[0]} vs ${gs[1]}`; $('metric-one-label').textContent = 'Log-rank χ²'; $('difference').textContent = result.statistic.toFixed(2); $('metric-one-note').textContent = `df = ${result.df}`; $('metric-two-label').textContent = 'Median survival'; $('ci').textContent = `${Number.isFinite(kmA.median) ? kmA.median : 'NR'} / ${Number.isFinite(kmB.median) ? kmB.median : 'NR'}`; $('metric-two-note').textContent = `${gs[0]} / ${gs[1]}`; $('p-value').textContent = result.pValue < .001 ? '< 0.001' : result.pValue.toFixed(3); $('significance').textContent = result.pValue < .05 ? 'Evidence of different survival distributions' : 'No strong evidence of different survival distributions'; $('assumption-text').textContent = 'Independent subjects · non-negative follow-up time · binary event indicator · censoring is assumed non-informative.'; lastResult = {...result,timeKey,eventKey,kmA,kmB}; renderResultDetails([['Method',result.method],['Time column',timeKey],['Event column',eventKey],['N',`${result.nA} + ${result.nB}`],['Events',`${kmA.events} + ${kmB.events}`],['P value',result.pValue.toFixed(4)]]); } catch (error) { $('significance').textContent = error.message; } return;
  }
  if (currentAnalysis === 'wilcoxon') {
    const columns = numericColumns(), beforeKey = columns[0], afterKey = columns[1];
    if (!beforeKey || !afterKey) { $('analysis-title').textContent = 'Add two matched numeric columns'; $('significance').textContent = 'A Wilcoxon signed-rank test needs two numeric measurements in the same rows'; return; }
    const pairs = data.map(row => [Number(row[beforeKey]), Number(row[afterKey])]).filter(pair => pair.every(Number.isFinite));
    try { const result = wilcoxonSignedRank(pairs.map(pair => pair[0]), pairs.map(pair => pair[1])); $('analysis-eyebrow').textContent = 'Analysis · Wilcoxon signed-rank test'; $('analysis-title').textContent = `${beforeKey} vs ${afterKey}`; $('metric-one-label').textContent = 'W statistic'; $('difference').textContent = result.w.toFixed(2); $('metric-one-note').textContent = `${result.n} non-zero pairs`; $('metric-two-label').textContent = 'Median change'; $('ci').textContent = result.medianDifference.toFixed(2); $('metric-two-note').textContent = 'first − second'; $('p-value').textContent = result.pValue < .001 ? '< 0.001' : result.pValue.toFixed(3); $('significance').textContent = result.pValue < .05 ? 'Evidence of a paired change' : 'No strong evidence of a paired change'; $('assumption-text').textContent = 'Matched rows · ordinal or continuous outcome · nonparametric paired comparison; zero differences are omitted.'; lastResult = result; renderResultDetails([['Method',result.method],['N',result.n],['W',result.w.toFixed(3)],['Median change',result.medianDifference.toFixed(4)],['z statistic',result.z.toFixed(3)],['P value',result.pValue.toFixed(4)]]); } catch (error) { $('significance').textContent = error.message; } return;
  }
  if (currentAnalysis === 'paired') {
    const columns = numericColumns(), beforeKey = columns[0], afterKey = columns[1];
    if (!beforeKey || !afterKey) { $('analysis-title').textContent = 'Add two numeric columns'; $('significance').textContent = 'A paired test needs two numeric measurements in the same rows'; return; }
    const pairs = data.map(row => [Number(row[beforeKey]), Number(row[afterKey])]).filter(pair => pair.every(Number.isFinite));
    try { const result = pairedTTest(pairs.map(pair => pair[0]), pairs.map(pair => pair[1])); $('analysis-eyebrow').textContent = 'Analysis · Paired t-test'; $('analysis-title').textContent = `${beforeKey} vs ${afterKey}`; $('metric-one-label').textContent = 'Mean paired change'; $('difference').textContent = result.meanDifference.toFixed(2); $('metric-one-note').textContent = `${result.n} matched rows`; $('metric-two-label').textContent = '95% CI'; $('ci').textContent = `${result.confidenceInterval95[0].toFixed(2)} to ${result.confidenceInterval95[1].toFixed(2)}`; $('metric-two-note').textContent = 'change = first − second'; $('p-value').textContent = result.pValue < .001 ? '< 0.001' : result.pValue.toFixed(3); $('significance').textContent = result.pValue < .05 ? 'Evidence of a paired change' : 'No strong evidence of a paired change'; $('assumption-text').textContent = 'Matched rows · numeric measurements · inspect the change scores for outliers and near-zero variance.'; lastResult = result; renderResultDetails([['Method',result.method],['N',result.n],['Mean change',result.meanDifference.toFixed(4)],['t statistic',result.t.toFixed(3)],['Degrees of freedom',result.df],['P value',result.pValue.toFixed(4)]]); } catch (error) { $('significance').textContent = error.message; } return;
  }
  if (currentAnalysis === 'friedman') {
    const columns = numericColumns(); if (columns.length < 3) { $('analysis-title').textContent = 'Add three matched numeric columns'; $('significance').textContent = 'A Friedman test needs at least three numeric measurements in the same rows'; return; }
    const matched = data.map(row => columns.map(column => Number(row[column]))).filter(row => row.every(Number.isFinite)), arrays = columns.map((_,index) => matched.map(row => row[index]));
    try { const result = friedmanTest(arrays); $('analysis-eyebrow').textContent = 'Analysis · Friedman test'; $('analysis-title').textContent = `${columns.length} matched conditions`; $('metric-one-label').textContent = 'χ² statistic'; $('difference').textContent = result.statistic.toFixed(2); $('metric-one-note').textContent = `df = ${result.df}`; $('metric-two-label').textContent = 'Matched rows'; $('ci').textContent = result.n; $('metric-two-note').textContent = 'complete cases'; $('p-value').textContent = result.pValue < .001 ? '< 0.001' : result.pValue.toFixed(3); $('significance').textContent = result.pValue < .05 ? 'Evidence of differences across matched conditions' : 'No strong evidence of differences'; $('assumption-text').textContent = 'Matched rows · ordinal or numeric measurements · nonparametric repeated-measures omnibus test.'; lastResult = result; renderResultDetails([['Method',result.method],['Conditions',result.conditions],['Matched N',result.n],['χ²',result.statistic.toFixed(4)],['Degrees of freedom',result.df],['P value',result.pValue.toFixed(4)]]); } catch (error) { $('significance').textContent = error.message; } return;
  }
  if (currentAnalysis === 'mannwhitney' && gs.length === 2) {
    const a=numbers(gs[0]), b=numbers(gs[1]); if(a.length<2||b.length<2){$('significance').textContent='Each group needs at least two numeric observations';return;} try { const result=mannWhitney(a,b); $('analysis-eyebrow').textContent='Analysis · Mann–Whitney U'; $('analysis-title').textContent=`${gs[0]} vs ${gs[1]}`; $('metric-one-label').textContent='U statistic'; $('difference').textContent=result.u.toFixed(1); $('metric-one-note').textContent=`${result.nA} vs ${result.nB} observations`; $('metric-two-label').textContent='Z statistic'; $('ci').textContent=result.z.toFixed(2); $('metric-two-note').textContent='normal approximation'; $('p-value').textContent=result.pValue<.001?'< 0.001':result.pValue.toFixed(3); $('significance').textContent=result.pValue<.05?'Evidence of a distributional difference':'No strong evidence of a distributional difference'; $('assumption-text').textContent='Independent observations · ordinal or numeric outcome · rank-based test with tie correction.'; lastResult=result; renderResultDetails([['Method',result.method],['N',`${result.nA} + ${result.nB}`],['U',result.u.toFixed(2)],['Z',result.z.toFixed(3)],['P value',result.pValue.toFixed(4)]]); } catch(error){$('significance').textContent=error.message;} return;
  }
  if (currentAnalysis === 'anova' && gs.length > 2) {
    const result = oneWayAnova(gs.map(numbers));
    $('analysis-eyebrow').textContent = 'Analysis · One-way ANOVA'; $('analysis-title').textContent = `${gs.length} groups`;
    $('metric-one-label').textContent = 'F statistic'; $('difference').textContent = result.f.toFixed(2); $('metric-one-note').textContent = `${result.dfBetween} and ${result.dfWithin} degrees of freedom`;
    $('metric-two-label').textContent = 'Grand mean'; $('ci').textContent = result.grandMean.toFixed(1); $('metric-two-note').textContent = 'across all groups';
    $('p-value').textContent = result.pValue < .001 ? '< 0.001' : result.pValue.toFixed(3); $('significance').textContent = result.pValue < .05 ? 'Evidence of differences among groups' : 'No strong evidence of differences';
    const pairwise = pairwiseWelch(gs.map(numbers), gs, multipleComparison); lastResult = {...result, pairwise}; renderResultDetails([['Method',result.method],['N',result.n],['F',result.f.toFixed(3)],['df',`${result.dfBetween}, ${result.dfWithin}`],['P value',result.pValue < .001 ? '< 0.001' : result.pValue.toFixed(4)],['Post-hoc',`${pairwise.length} ${multipleComparison}-adjusted comparisons`]]); return;
  }
  if (currentAnalysis === 'two-way') {
    const categorical=[...new Set(data.flatMap(row=>Object.keys(row)))].filter(key=>key!==roleKeys.group&&data.some(row=>row[key]!=null&&!Number.isFinite(Number(row[key]))&&new Set(data.map(item=>item[key]).filter(value=>value!=null).map(String)).size>1)), factorA=roleKeys.group, factorB=categorical[0];
    if (!factorA || !factorB || !roleKeys.value) { $('analysis-title').textContent='Add two categorical factors'; $('significance').textContent='Two-way ANOVA needs two categorical factor columns and a numeric outcome'; return; }
    try { const result=twoWayAnova(data,factorA,factorB,roleKeys.value), pMin=Math.min(result.pA,result.pB,result.pInteraction); $('analysis-eyebrow').textContent='Analysis · Two-way ANOVA'; $('analysis-title').textContent=`${factorA} × ${factorB}`; $('metric-one-label').textContent=`${factorA} F`; $('difference').textContent=result.fA.toFixed(2); $('metric-one-note').textContent=`p ${result.pA<.001?'< 0.001':result.pA.toFixed(3)}`; $('metric-two-label').textContent=`${factorB} F`; $('ci').textContent=result.fB.toFixed(2); $('metric-two-note').textContent=`p ${result.pB<.001?'< 0.001':result.pB.toFixed(3)}`; $('p-value').textContent=pMin<.001?'< 0.001':pMin.toFixed(3); $('significance').textContent=result.pInteraction<.05?'Evidence of an interaction or main effect':'No strong evidence of a main effect or interaction'; $('assumption-text').textContent='Independent observations · balanced factorial cells · numeric outcome · inspect the interaction plot before interpretation.'; lastResult=result; renderResultDetails([['Method',result.method],['N',result.n],['Factor A',`${factorA}: F = ${result.fA.toFixed(3)}, p = ${result.pA.toFixed(4)}`],['Factor B',`${factorB}: F = ${result.fB.toFixed(3)}, p = ${result.pB.toFixed(4)}`],['Interaction',`F = ${result.fInteraction.toFixed(3)}, p = ${result.pInteraction.toFixed(4)}`],['Error df',result.dfError]]); } catch(error) { $('significance').textContent=error.message; } return;
  }
  if (currentAnalysis === 'kruskal' && gs.length > 2) {
    try { const result = kruskalWallis(gs.map(numbers)); $('analysis-eyebrow').textContent = 'Analysis · Kruskal–Wallis'; $('analysis-title').textContent = `${gs.length} groups`; $('metric-one-label').textContent = 'H statistic'; $('difference').textContent = result.h.toFixed(2); $('metric-one-note').textContent = `χ² approximation · df = ${result.df}`; $('metric-two-label').textContent = 'Observations'; $('ci').textContent = result.n; $('metric-two-note').textContent = 'ranked observations'; $('p-value').textContent = result.pValue < .001 ? '< 0.001' : result.pValue.toFixed(3); $('significance').textContent = result.pValue < .05 ? 'Evidence of distributional differences' : 'No strong evidence of distributional differences'; $('assumption-text').textContent = 'Independent observations · ordinal or numeric outcome · rank-based omnibus test with tie correction.'; lastResult = result; renderResultDetails([['Method',result.method],['N',result.n],['H statistic',result.h.toFixed(4)],['Degrees of freedom',result.df],['P value',result.pValue.toFixed(4)],['Tie correction',result.tieCorrection.toFixed(4)]]); } catch (error) { $('significance').textContent = error.message; } return;
  }
  if (currentAnalysis === 'chi-square') {
    const categorical = [...new Set(data.flatMap(row => Object.keys(row)))].filter(key => key !== 'group' && data.some(row => row[key] != null && !Number.isFinite(Number(row[key]))));
    const outcome = categorical[0];
    if (!outcome || !gs.length) { $('analysis-title').textContent = 'Add categorical outcome data'; $('significance').textContent = 'A chi-square test needs a group column and a second categorical column'; return; }
    const levels = [...new Set(data.map(row => row[outcome]).filter(value => value != null).map(String))], table = gs.map(group => levels.map(level => data.filter(row => String(row.group) === String(group) && String(row[outcome]) === level).length));
    try { const result = chiSquareTest(table); const minExpected = Math.min(...result.expected.flat()); $('analysis-eyebrow').textContent = 'Analysis · Pearson chi-square'; $('analysis-title').textContent = `${outcome} by group`; $('metric-one-label').textContent = 'χ² statistic'; $('difference').textContent = result.statistic.toFixed(2); $('metric-one-note').textContent = `${result.df} degrees of freedom`; $('metric-two-label').textContent = 'Observations'; $('ci').textContent = result.n; $('metric-two-note').textContent = `${levels.length} outcome levels`; $('p-value').textContent = result.pValue < .001 ? '< 0.001' : result.pValue.toFixed(3); $('significance').textContent = result.pValue < .05 ? 'Evidence of an association' : 'No strong evidence of an association'; $('assumption-text').textContent = minExpected < 5 ? `Warning: the smallest expected count is ${minExpected.toFixed(1)}. Consider combining sparse levels or using an exact test.` : 'Independent observations · categorical counts · all expected counts are at least 5.'; lastResult = {...result, outcome}; renderResultDetails([['Method',result.method],['Table',`${gs.length} × ${levels.length}`],['N',result.n],['χ²',result.statistic.toFixed(4)],['Degrees of freedom',result.df],['P value',result.pValue.toFixed(4)],['Smallest expected',minExpected.toFixed(2)]]); } catch (error) { $('significance').textContent = error.message; } return;
  }
  if (currentAnalysis === 'fisher') {
    const categorical = [...new Set(data.flatMap(row => Object.keys(row)))].filter(key => key !== roleKeys.group && data.some(row => row[key] != null && !Number.isFinite(Number(row[key])))), outcome = categorical[0], levels = outcome ? [...new Set(data.map(row => row[outcome]).filter(value => value != null).map(String))] : [];
    if (!outcome || gs.length !== 2 || levels.length !== 2) { $('analysis-title').textContent = 'Set up a 2 × 2 table'; $('significance').textContent = 'Fisher’s exact test needs two groups and exactly two categorical outcome levels'; return; }
    const table = gs.map(group => levels.map(level => data.filter(row => String(row[roleKeys.group]) === String(group) && String(row[outcome]) === level).length));
    try { const result = fisherExactTest(table); $('analysis-eyebrow').textContent = 'Analysis · Fisher’s exact test'; $('analysis-title').textContent = `${outcome} by ${roleKeys.group}`; $('metric-one-label').textContent = 'Odds ratio'; $('difference').textContent = Number.isFinite(result.oddsRatio) ? result.oddsRatio.toFixed(2) : '∞'; $('metric-one-note').textContent = 'first level vs second level'; $('metric-two-label').textContent = 'Observations'; $('ci').textContent = result.n; $('metric-two-note').textContent = '2 × 2 table'; $('p-value').textContent = result.pValue < .001 ? '< 0.001' : result.pValue.toFixed(3); $('significance').textContent = result.pValue < .05 ? 'Evidence of an association' : 'No strong evidence of an association'; $('assumption-text').textContent = 'Independent observations · exact test for a 2 × 2 table · suitable when expected counts are small.'; lastResult = {...result, outcome, levels}; renderResultDetails([['Method',result.method],['Table',`${gs.length} × ${levels.length}`],['N',result.n],['Odds ratio',Number.isFinite(result.oddsRatio) ? result.oddsRatio.toFixed(4) : 'infinite'],['P value',result.pValue.toFixed(4)]]); } catch (error) { $('significance').textContent = error.message; } return;
  }
  if (currentAnalysis === 'descriptive' || gs.length !== 2) {
    $('analysis-eyebrow').textContent = 'Analysis · Descriptive statistics'; $('analysis-title').textContent = 'Choose a comparison when ready'; $('metric-one-label').textContent = 'Groups'; $('difference').textContent = gs.length; $('metric-one-note').textContent = 'detected in this table'; $('metric-two-label').textContent = 'Observations'; $('ci').textContent = data.length; $('metric-two-note').textContent = 'rows in project'; $('p-value').textContent = '—'; $('significance').textContent = 'No inferential test selected'; lastResult = null; renderResultDetails(); return;
  }
  const a = numbers(gs[0]), b = numbers(gs[1]);
  if (a.length < 2 || b.length < 2) { $('significance').textContent = 'Each group needs at least two numeric observations'; return; }
    try {
      const result = currentAnalysis === 'student' ? studentTTest(a, b) : welchTTest(a, b);
      $('analysis-eyebrow').textContent = `Analysis · ${result.method}`; $('analysis-title').textContent = `${gs[0]} vs ${gs[1]}`; $('metric-one-label').textContent = 'Difference in means'; $('difference').textContent = `${result.difference < 0 ? '−' : ''}${Math.abs(result.difference).toFixed(1)}`; $('metric-one-note').textContent = 'percentage points'; $('metric-two-label').textContent = '95% CI'; $('ci').textContent = `${result.confidenceInterval95[0] < 0 ? '−' : ''}${Math.abs(result.confidenceInterval95[0]).toFixed(1)} to ${result.confidenceInterval95[1] < 0 ? '−' : ''}${Math.abs(result.confidenceInterval95[1]).toFixed(1)}`; $('metric-two-note').textContent = `${currentAnalysis === 'student' ? 'Student pooled' : 'Welch'} confidence interval`; $('p-value').textContent = result.pValue < .001 ? '< 0.001' : result.pValue.toFixed(3); $('significance').textContent = result.pValue < .05 ? 'Evidence of a difference' : 'No strong evidence of a difference'; $('assumption-text').textContent = currentAnalysis === 'student' ? 'Independent observations · numeric outcome · equal-variance assumption · review group spreads before interpreting.' : 'Two independent groups · numeric outcome · no zero-variance group. Review the raw points before interpreting.'; lastResult=result; renderResultDetails([['Method',result.method],['N',`${result.nA} + ${result.nB}`],['Difference',result.difference.toFixed(4)],['Cohen’s d',result.effectSizeCohensD.toFixed(4)],['t statistic',result.t.toFixed(3)],['Degrees of freedom',result.df.toFixed(2)],['P value',result.pValue.toFixed(4)]]);
  } catch (error) { $('significance').textContent = error.message; }
}
function renderFigure() { const chart = $('chart'); const xy = ['scatter','line','dose-response'].includes(figure.type) && figure.xKey && figure.yKey; const figureData = {...figure,groupKey:roleKeys.group,valueKey:roleKeys.value}; let svg; if (figure.panels && figure.panels.length > 1) svg=renderLayoutSvg(data, figureData); else if (figure.type === 'survival') svg=renderSurvivalSvg(data, figureData); else if (figure.type === 'heatmap') svg=renderHeatmapSvg(data, figureData); else if (figure.type === 'correlation') svg=renderCorrelationMatrixSvg(data, figureData); else if (figure.type === 'residual') svg=renderResidualSvg(data, figureData); else if (figure.type === 'qq' || figure.type === 'qq-quantile') svg=renderQqSvg(data, figureData); else if (figure.type === 'ecdf') svg=renderEcdfSvg(data, figureData); else if (figure.type === 'bland-altman') svg=renderBlandAltmanSvg(data, figureData); else if (xy) svg=renderXYSvg(data, figureData); else svg=renderGroupedSvg(data, figureData); chart.outerHTML = svg; }
function persistAndRenderDerived() { localStorage.setItem('statista-data', JSON.stringify(data)); localStorage.setItem('statista-figure', JSON.stringify(figure)); renderStats(); renderFigure(); renderAnalysis(); $('obs-count').textContent = data.length; const count = $('history-count'); if (count) count.textContent = `${analysisHistory.length} saved`; }
function refresh() { persistAndRenderDerived(); renderTable(); }
function toast(message) { const element = $('toast'); element.textContent = message; element.classList.add('show'); setTimeout(() => element.classList.remove('show'), 2200); }
function download(content, name, type) { const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([content], {type})); link.download = name; link.click(); URL.revokeObjectURL(link.href); toast(`Downloaded ${name}`); }
const navTargets = {workspace:'.page-heading',data:'.table-panel',analysis:'.analysis-panel',figures:'.chart-panel'};
document.querySelectorAll('.nav-item').forEach(button => button.onclick = () => { document.querySelectorAll('.nav-item').forEach(item => item.classList.toggle('active', item === button)); document.querySelector(navTargets[button.dataset.view] || '.page-heading')?.scrollIntoView({behavior:'smooth',block:'start'}); });

$('new-project').insertAdjacentHTML('beforebegin', '<button class="quiet" id="undo" title="Undo (⌘/Ctrl+Z)">Undo</button><button class="quiet" id="redo" title="Redo (⌘/Ctrl+Shift+Z)">Redo</button>');
$('analysis-method').insertAdjacentHTML('beforeend', '<option value="kruskal">Kruskal–Wallis</option>');
$('analysis-method').insertAdjacentHTML('beforeend', '<option value="student">Student t-test (equal variance)</option>');
$('analysis-method').insertAdjacentHTML('beforeend', '<option value="paired">Paired t-test</option>');
$('analysis-method').insertAdjacentHTML('beforeend', '<option value="wilcoxon">Wilcoxon signed-rank</option>');
$('analysis-method').insertAdjacentHTML('beforeend', '<option value="spearman">Spearman rank correlation</option>');
$('analysis-method').insertAdjacentHTML('beforeend', '<option value="chi-square">Pearson chi-square</option>');
$('analysis-method').insertAdjacentHTML('beforeend', '<option value="fisher">Fisher’s exact test</option>');
$('analysis-method').insertAdjacentHTML('beforeend', '<option value="survival">Survival / log-rank</option>');
$('analysis-method').insertAdjacentHTML('beforeend', '<option value="friedman">Friedman repeated-measures</option>');
$('analysis-method').insertAdjacentHTML('beforeend', '<option value="two-way">Two-way ANOVA</option>');
$('analysis-method').insertAdjacentHTML('afterend', '<label class="role-label">Post-hoc <select id="multiple-comparison"><option value="Holm">Holm</option><option value="Benjamini–Hochberg">Benjamini–Hochberg</option></select></label>');
$('multiple-comparison').value = multipleComparison;
$('multiple-comparison').onchange = event => { checkpoint(); multipleComparison = event.target.value; localStorage.setItem('statista-multiple-comparison', multipleComparison); renderAnalysis(); };
$('undo').onclick=undo;$('redo').onclick=redo;updateHistoryButtons();document.addEventListener('keydown',event=>{if(!(event.metaKey||event.ctrlKey)||event.key.toLowerCase()!=='z')return;event.preventDefault();event.shiftKey?redo():undo();});
$('add-row').onclick = () => { checkpoint(); data.push({group: groups()[0] || 'Group A', value: null}); refresh(); };
$('add-column').onclick = () => { const name = prompt('New column name', `Column ${Object.keys(data[0] || {}).length + 1}`); if (!name) return; const key = name.trim().toLowerCase().replace(/\s+/g, '_'); if (!key) return; checkpoint(); data.forEach(row => row[key] = null); refresh(); toast(`Added ${key}`); };
$('table-mode').insertAdjacentHTML('afterend', '<label class="role-label">Group <select id="group-role"></select></label><label class="role-label">Outcome <select id="value-role"></select></label>');
$('group-role').onchange=event=>{checkpoint();roleKeys.group=event.target.value;localStorage.setItem('statista-role-keys',JSON.stringify(roleKeys));refresh();};$('value-role').onchange=event=>{checkpoint();roleKeys.value=event.target.value;localStorage.setItem('statista-role-keys',JSON.stringify(roleKeys));refresh();};
$('table-filter').oninput = event => { tableFilter = event.target.value; renderTable(); };
$('table-mode').value = tableMode; $('table-mode-label').textContent = tableMode.replace(/^./, letter => letter.toUpperCase()); $('table-mode').onchange = event => { tableMode = event.target.value; localStorage.setItem('statista-table-mode', tableMode); $('table-mode-label').textContent = tableMode.replace(/^./, letter => letter.toUpperCase()); toast(`Table mode: ${tableMode}`); };
$('transform-column').onclick = () => { const column = prompt('Column to transform', 'value'); const operation = prompt('Transformation: log10, sqrt, zscore, or percent_of_max', 'log10'); if (!column || !operation) return; try { const derivedKey = `${column.trim()}_${operation.trim()}`; const derived = transformNumericColumn(data, column.trim(), operation.trim()); checkpoint(); data = derived.map(row => ({...row, [derivedKey]: row[column.trim()]})); refresh(); toast(`Created derived column ${derivedKey}`); } catch (error) { toast(error.message); } };
$('chart-type').onchange = event => { checkpoint(); figure.type = event.target.value; if (figure.type === 'scatter' || figure.type === 'line' || figure.type === 'dose-response' || figure.type === 'residual' || figure.type === 'bland-altman') { const columns = numericColumns(); figure.xKey ||= columns[0]; figure.yKey ||= columns[1]; } if (figure.panels?.length === 1) figure.panels[0].type = figure.type; persistAndRenderDerived(); };
$('analysis-method').onchange = event => { checkpoint(); currentAnalysis = event.target.value; renderAnalysis(); };
$('rerun').onclick = () => { refresh(); recordAnalysis(); toast('Analysis re-run from current data'); };
$('edit-title').onclick = () => { const title = prompt('Figure/table title', $('table-title').textContent); if (title) { $('table-title').textContent = title; toast('Title updated'); } };
$('new-project').onclick = () => { if (confirm('Start a new project?')) { checkpoint(); data = []; refresh(); toast('New project started'); } };
$('csv-input').onchange = event => { const file = event.target.files[0]; if (!file) return; const isWorkbook = /\.(xlsx|xls)$/i.test(file.name); const reader = new FileReader(); reader.onload = () => { try { let headers, rows; if (isWorkbook) { const workbook = XLSX.read(reader.result, {type: 'array', cellDates: true}); const sheetName = workbook.SheetNames[0]; const matrix = XLSX.utils.sheet_to_json(workbook.Sheets[sheetName], {header: 1, defval: ''}); headers = (matrix.shift() || []).map((header, i) => String(header || `Column ${i + 1}`)); rows = matrix; toast(`Loaded worksheet “${sheetName}”`); } else { const parsed = parseDelimited(reader.result); headers = parsed.headers; rows = parsed.rows; } checkpoint(); data = rows.map(row => Object.fromEntries(headers.map((header, i) => { const raw = row[i] ?? ''; const key = String(header).trim().toLowerCase().replace(/\s+/g, '_'); return [key, raw === '' ? null : (Number.isFinite(Number(raw)) ? Number(raw) : raw)]; }))); const roles = inferAnalysisRoles(data); if (roles.groupKey) data.forEach(row => row.group = row[roles.groupKey] ?? 'Group'); if (roles.outcomeKey) data.forEach(row => row.value = row[roles.outcomeKey] == null ? null : Number(row[roles.outcomeKey])); if (!roles.groupKey) data.forEach(row => row.group = 'Group'); if (!roles.outcomeKey) data.forEach(row => row.value = null); refresh(); toast(`Imported ${data.length} rows`); } catch (error) { toast(`Import failed: ${error.message}`); } }; isWorkbook ? reader.readAsArrayBuffer(file) : reader.readAsText(file); };
$('project-input').onchange = event => { const file = event.target.files[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { try { const project = parseProject(reader.result); checkpoint(); data = project.data; analysisHistory = project.analysisHistory || []; figureLibrary = project.figures || []; roleKeys = project.roles || {group:'group',value:'value'}; multipleComparison = project.analysis?.multipleComparison || 'Holm'; localStorage.setItem('statista-role-keys',JSON.stringify(roleKeys)); localStorage.setItem('statista-multiple-comparison',multipleComparison); localStorage.setItem('statista-figure-library',JSON.stringify(figureLibrary)); figure = createFigure(project.figure || {}); currentAnalysis = ['anova','two-way','kruskal','mannwhitney','paired','wilcoxon','student','chi-square','fisher','survival','friedman','correlation','spearman','regression','descriptive'].includes(project.analysis?.method) ? project.analysis.method : 'welch'; if (supportedPlotTypes.has(figure.type)) $('chart-type').value = figure.type; document.title = `${project.projectTitle} — Statista`; $('project-title').textContent = project.projectTitle; refresh(); syncFigureControls(); renderFigureLibrary(); toast('Project opened'); } catch (error) { toast(error.message); } }; reader.readAsText(file); };
$('download-csv').onclick = () => { const headers = [...new Set(data.flatMap(row => Object.keys(row)))]; download(toCsv(headers, data.map(row => headers.map(key => row[key] ?? ''))), 'statista-data.csv', 'text/csv'); };
$('download-csv').insertAdjacentHTML('afterend', '<button class="text-button" id="download-xlsx">Download XLSX</button>');
$('download-xlsx').onclick = () => { const worksheet = XLSX.utils.json_to_sheet(data); const workbook = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(workbook, worksheet, 'Statista data'); const bytes = XLSX.write(workbook, {bookType: 'xlsx', type: 'array'}); download(bytes, 'statista-data.xlsx', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'); };
$('download-svg').onclick = () => download(new XMLSerializer().serializeToString($('chart')), 'statista-figure.svg', 'image/svg+xml');
$('download-svg').insertAdjacentHTML('beforebegin', '<button class="text-button" id="print-figure">Print / PDF</button>');
$('print-figure').onclick = () => window.print();
$('export-project').onclick = () => download(serializeProject(createProject({title: $('project-title').textContent, data, analysis: {method: currentAnalysis, groups: groups(), roles: roleKeys, variables: {group: roleKeys.group, outcome: roleKeys.value, x: figure.xKey || null, y: figure.yKey || null}, exclusions: {missingOutcome: data.filter(row => !Number.isFinite(Number(row[roleKeys.value]))).length}, multipleComparison, options: {tableMode, figureType: figure.type}}, analysisHistory, roles: roleKeys, figure, figures: figureLibrary})), 'statista-project.json', 'application/json');
$('export-project').insertAdjacentHTML('beforebegin', '<button id="download-methods" class="quiet">Methods text</button>');
$('download-methods').onclick = () => download(`${$('project-title').textContent}\n\n${currentMethods()}\n`, 'statista-methods.txt', 'text/plain');
$('download-methods').insertAdjacentHTML('afterend', '<button id="download-result" class="quiet">Result JSON</button>');
$('download-result').onclick = () => { if (!lastResult) { toast('Run an analysis before exporting a result'); return; } download(JSON.stringify({projectTitle:$('project-title').textContent,exportedAt:new Date().toISOString(),method:currentAnalysis,roles:roleKeys,result:lastResult,methods:currentMethods()},null,2), 'statista-result.json', 'application/json'); };
$('download-svg').insertAdjacentHTML('beforebegin', '<button class="text-button" id="download-png">PNG</button><button class="text-button" id="download-jpeg">JPEG</button>');
function rasterExport(type, extension){const svgText=new XMLSerializer().serializeToString($('chart'));const image=new Image();image.onload=()=>{const canvas=document.createElement('canvas');canvas.width=figure.width*2;canvas.height=figure.height*2;const ctx=canvas.getContext('2d');ctx.scale(2,2);ctx.fillStyle='#ffffff';ctx.fillRect(0,0,figure.width,figure.height);ctx.drawImage(image,0,0);canvas.toBlob(blob=>{const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`statista-figure.${extension}`;link.click();URL.revokeObjectURL(link.href);toast(`Downloaded statista-figure.${extension}`)},type,.95)};image.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svgText)}
$('download-svg').insertAdjacentHTML('beforebegin', '<button class="text-button" id="download-tiff">TIFF</button>');
$('download-png').onclick=()=>rasterExport('image/png','png');$('download-jpeg').onclick=()=>rasterExport('image/jpeg','jpg');$('download-tiff').onclick=()=>{const svgText=new XMLSerializer().serializeToString($('chart'));const image=new Image();image.onload=()=>{const canvas=document.createElement('canvas');canvas.width=figure.width*2;canvas.height=figure.height*2;const ctx=canvas.getContext('2d');ctx.scale(2,2);ctx.fillStyle='#ffffff';ctx.fillRect(0,0,figure.width,figure.height);ctx.drawImage(image,0,0);const blob=new Blob([encodeRgbTiff(canvas.width,canvas.height,ctx.getImageData(0,0,canvas.width,canvas.height).data)],{type:'image/tiff'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='statista-figure.tiff';link.click();URL.revokeObjectURL(link.href);toast('Downloaded statista-figure.tiff')};image.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svgText)};
try{validateFigure(figure)}catch{figure=createFigure()}
$('history-count').textContent = analysisHistory.length ? `${analysisHistory.length} saved` : '0 saved';
$('results-detail')?.remove(); document.querySelector('.analysis-panel').insertAdjacentHTML('beforeend', '<div id="results-detail" class="results-detail"></div>');
const supportedPlotTypes = new Set(['dot','bar','box','violin','swarm','histogram','density','scatter','line','connected-dot','mean-ci','mean-sem','mean-sd','point-range','errorbar','area','step','spline','ecdf','lollipop','survival','dose-response','qq','qq-quantile','bland-altman','heatmap','correlation','residual']);
$('chart-type').innerHTML = PLOT_TYPES.filter(([id]) => supportedPlotTypes.has(id)).map(([id,label]) => `<option value="${id}">${label}</option>`).join('');
$('chart-type').value = supportedPlotTypes.has(figure.type) ? figure.type : 'dot'; figure.type = $('chart-type').value;
$('chart').parentElement.insertAdjacentHTML('afterend', '<div class="figure-editor"><label>Figure title <input id="figure-title" type="text" value="Viability response" /></label><label>Control <input id="figure-color-a" type="color" value="#3f79c9" /></label><label>Treatment <input id="figure-color-b" type="color" value="#e77d69" /></label></div>');
$('figure-title').parentElement.insertAdjacentHTML('afterend', '<label>Panels <select id="panel-count"><option value="1">1</option><option value="2">2</option><option value="4">4</option></select></label>');
$('figure-title').parentElement.insertAdjacentHTML('afterend', '<div id="panel-controls" class="panel-controls"></div>');
$('figure-title').parentElement.insertAdjacentHTML('afterend', '<div class="figure-library-controls"><button class="quiet" id="save-figure">Save figure variant</button><div id="figure-library" class="figure-library"></div></div>');
$('figure-title').parentElement.insertAdjacentHTML('afterend', '<label>Style <select id="figure-template"><option value="journal">Journal</option><option value="presentation">Presentation</option><option value="minimal">Minimal</option></select></label>');
$('figure-title').parentElement.insertAdjacentHTML('afterend', '<label>X label <input id="figure-x-label" type="text" /></label><label>Y label <input id="figure-y-label" type="text" /></label><label><input id="figure-show-mean" type="checkbox" /> Show means</label>');
$('figure-title').value = figure.title; $('figure-color-a').value = figure.colors[0]; $('figure-color-b').value = figure.colors[1];
$('figure-x-label').value = figure.xLabel; $('figure-y-label').value = figure.yLabel;
$('figure-show-mean').checked = figure.showMean;
const figureColumns = [...new Set(data.flatMap(row => Object.keys(row)))].filter(key => data.some(row => Number.isFinite(Number(row[key])))); $('figure-title').parentElement.insertAdjacentHTML('afterend', `<label>X <select id="figure-x">${figureColumns.map(key => `<option value="${key}">${key}</option>`).join('')}</select></label><label>Y <select id="figure-y">${figureColumns.map(key => `<option value="${key}">${key}</option>`).join('')}</select></label>`); if (figure.xKey) $('figure-x').value = figure.xKey; if (figure.yKey) $('figure-y').value = figure.yKey;
$('figure-show-mean').parentElement.insertAdjacentHTML('afterend', '<label>Point size <input id="figure-point-size" type="number" min="1" max="20" step="1" /></label><label>Line width <input id="figure-stroke-width" type="number" min="0.5" max="8" step="0.5" /></label><label>Y min <input id="figure-y-min" type="number" step="any" placeholder="auto" /></label><label>Y max <input id="figure-y-max" type="number" step="any" placeholder="auto" /></label><label>Annotation <input id="figure-annotation" type="text" placeholder="e.g. p = 0.03" /></label><button class="text-button" id="add-annotation">＋ Add</button><div id="annotation-list"></div>');
$('figure-point-size').value = figure.pointSize; $('figure-stroke-width').value = figure.strokeWidth; $('figure-y-min').value = Number.isFinite(figure.yMin) ? figure.yMin : ''; $('figure-y-max').value = Number.isFinite(figure.yMax) ? figure.yMax : '';
function renderAnnotationList(){const target=$('annotation-list');if(!target)return;target.innerHTML=(figure.annotations||[]).map((annotation,index)=>`<button class="text-button" data-remove-annotation="${index}" title="Remove annotation">${annotation.label||'annotation'} ×</button>`).join(' ');target.querySelectorAll('[data-remove-annotation]').forEach(button=>button.onclick=()=>{checkpoint();figure.annotations.splice(Number(button.dataset.removeAnnotation),1);persistAndRenderDerived();renderAnnotationList();});}
renderAnnotationList();
$('save-figure').onclick=()=>{const title=prompt('Name this figure variant',figure.title||`Figure ${figureLibrary.length+1}`);if(!title)return;figureLibrary=[...figureLibrary,{...JSON.parse(JSON.stringify(figure)),title}];localStorage.setItem('statista-figure-library',JSON.stringify(figureLibrary));renderFigureLibrary();toast(`Saved ${title}`);};
renderFigureLibrary();
$('add-annotation').onclick=()=>{const label=$('figure-annotation').value.trim();if(!label)return;checkpoint();figure.annotations=[...(figure.annotations||[]),{label,x1:170,x2:430,y:45+figure.annotations.length*24}];$('figure-annotation').value='';persistAndRenderDerived();renderAnnotationList();};
[['figure-point-size','pointSize'],['figure-stroke-width','strokeWidth']].forEach(([id,key])=>$(id).addEventListener('change',event=>{checkpoint();figure[key]=Number(event.target.value);persistAndRenderDerived();}));
[['figure-y-min','yMin'],['figure-y-max','yMax']].forEach(([id,key])=>$(id).addEventListener('change',event=>{checkpoint();figure[key]=event.target.value===''?null:Number(event.target.value);persistAndRenderDerived();}));
['figure-x','figure-y'].forEach(id => $(id).addEventListener('change', event => { checkpoint(); figure[id === 'figure-x' ? 'xKey' : 'yKey'] = event.target.value; persistAndRenderDerived(); }));
$('figure-show-mean').onchange = event => { checkpoint(); figure.showMean = event.target.checked; persistAndRenderDerived(); };
const panelCount = figure.panels?.length || 1; $('panel-count').value = String(panelCount);
if (figure.template) $('figure-template').value = figure.template;
$('figure-template').onchange = event => { checkpoint(); figure = applyFigureTemplate(figure, event.target.value); $('figure-title').value = figure.title; $('figure-color-a').value = figure.colors[0]; $('figure-color-b').value = figure.colors[1]; persistAndRenderDerived(); toast(`${event.target.value} figure style applied`); };
if (!figure.panels || figure.panels.length !== panelCount) figure.panels = [{type:figure.type,title:figure.title}];
renderPanelControls();
$('panel-count').onchange = event => { checkpoint(); const count=Number(event.target.value), types=['dot','box','histogram','line']; figure.panels=Array.from({length:count},(_,i)=>({type:types[i%types.length],title:i===0?figure.title:`Panel ${i+1}`})); renderPanelControls(); persistAndRenderDerived(); toast(`Figure now has ${count} panel${count===1?'':'s'}`); };
['figure-title','figure-color-a','figure-color-b','figure-x-label','figure-y-label'].forEach(id => { $(id).addEventListener('focus', () => checkpoint()); $(id).addEventListener('input', event => { if(id === 'figure-title') figure.title = event.target.value; if(id === 'figure-color-a') figure.colors[0] = event.target.value; if(id === 'figure-color-b') figure.colors[1] = event.target.value; if(id === 'figure-x-label') figure.xLabel = event.target.value; if(id === 'figure-y-label') figure.yLabel = event.target.value; document.querySelector('.chart-panel h3').textContent = figure.title; persistAndRenderDerived(); }); });
refresh();
