import test from 'node:test';import assert from 'node:assert/strict';import{renderGroupedSvg,renderLayoutSvg,renderXYSvg,renderSurvivalSvg,renderHeatmapSvg,renderCorrelationMatrixSvg,renderResidualSvg,renderQqSvg,renderEcdfSvg,renderBlandAltmanSvg}from'../src/core/renderer.js';
const data=[{group:'A',value:1},{group:'A',value:2},{group:'B',value:4},{group:'B',value:5}];
test('renderer emits accessible SVG for dot and bar figures',()=>{for(const type of ['dot','bar','box','histogram','line']){const svg=renderGroupedSvg(data,{type,title:'Test'});assert.match(svg,/xmlns="http:\/\/www.w3.org\/2000\/svg/);assert.match(svg,/<title>Test<\/title>/);assert.match(svg,/A/);assert.match(svg,/B/)}});
test('renderer includes editable labels and significance annotations',()=>{const svg=renderGroupedSvg(data,{type:'dot',title:'Outcome',xLabel:'Condition',yLabel:'Response',annotations:[{x1:120,x2:300,y:50,label:'p = 0.01'}]});assert.match(svg,/Condition/);assert.match(svg,/Response/);assert.match(svg,/p = 0.01/);assert.match(svg,/<path/)})
test('renderer escapes labels',()=>{assert.match(renderGroupedSvg([{group:'<bad>',value:1}],{type:'dot'}),/&lt;bad&gt;/)});
test('renderer composes editable multi-panel figures',()=>{const svg=renderLayoutSvg(data,{title:'Figure 1',panels:[{type:'dot',title:'Raw'},{type:'box',title:'Summary'}]});assert.match(svg,/translate\(/);assert.match(svg,/Raw/);assert.match(svg,/Summary/)})
test('XY renderer maps numeric columns to an accessible figure',()=>{const svg=renderXYSvg([{dose:1,response:2},{dose:2,response:4},{dose:3,response:6}],{type:'scatter',xKey:'dose',yKey:'response',title:'Dose response'});assert.match(svg,/Dose response/);assert.match(svg,/circle/);assert.match(svg,/dose/);assert.match(svg,/response/)})
test('renderer supports distribution, uncertainty, and empirical plot layers',()=>{for(const type of ['violin','swarm','mean-ci','mean-sem','mean-sd','connected-dot','lollipop','density','point-range','errorbar','area','step','spline','ecdf']){const svg=renderGroupedSvg(data,{type,title:'Layer'});assert.match(svg,/<svg/);assert.match(svg,/Layer/)}})
test('renderer can overlay group means',()=>{const svg=renderGroupedSvg(data,{type:'dot',showMean:true});assert.match(svg,/stroke-width="2.5"/)})
test('survival renderer emits Kaplan–Meier step curves',()=>{const svg=renderSurvivalSvg([{group:'A',time:1,event:1},{group:'A',time:2,event:0},{group:'A',time:3,event:1},{group:'B',time:1,event:0},{group:'B',time:2,event:1},{group:'B',time:4,event:1}],{timeKey:'time',eventKey:'event',title:'Survival'});assert.match(svg,/Survival/);assert.match(svg,/polyline/);assert.match(svg,/Survival probability/);assert.match(svg,/points="60,35 193,35/)})
test('matrix renderers preserve variable labels and values',()=>{const rows=[{group:'A',x:1,y:2,z:3},{group:'B',x:2,y:4,z:5},{group:'C',x:3,y:6,z:7}];const heatmap=renderHeatmapSvg(rows,{columns:['x','y','z'],title:'Heat'}),matrix=renderCorrelationMatrixSvg(rows,{columns:['x','y','z'],title:'Correlations'});assert.match(heatmap,/Heat/);assert.match(heatmap,/x/);assert.match(matrix,/Correlations/);assert.match(matrix,/1\.00/)})
test('residual renderer displays a zero baseline and residual points',()=>{const svg=renderResidualSvg([{x:1,value:2},{x:2,value:4.5},{x:3,value:5.5},{x:4,value:8}],{xKey:'x',yKey:'value',title:'Residuals'});assert.match(svg,/Residuals/);assert.match(svg,/Residual/);assert.match(svg,/stroke-dasharray/);assert.match(svg,/circle/)})
test('ECDF, Q–Q, and Bland–Altman renderers expose diagnostic figures',()=>{const rows=[{group:'A',x:1,value:1.2},{group:'A',x:2,value:2.1},{group:'B',x:3,value:2.9},{group:'B',x:4,value:4.2},{group:'B',x:5,value:5.1}];const ecdf=renderEcdfSvg(rows,{groupKey:'group',valueKey:'value',title:'Distribution'}),qq=renderQqSvg(rows,{valueKey:'value',title:'Normality'}),ba=renderBlandAltmanSvg(rows,{xKey:'x',yKey:'value',title:'Agreement'});assert.match(ecdf,/Cumulative probability/);assert.match(qq,/Theoretical quantiles/);assert.match(ba,/Mean of paired measurements/)})
