import test from 'node:test';import assert from 'node:assert/strict';import{mean,variance,descriptiveSummary,studentTQuantile,welchTTest,studentTTest,oneWayAnova,twoWayAnova,pairedTTest,wilcoxonSignedRank,mannWhitney,pearsonCorrelation,spearmanCorrelation,linearRegression,fitFourParameterLogistic,holmAdjust,pairwiseWelch,benjaminiHochberg,kruskalWallis,friedmanTest,chiSquareTest,fisherExactTest,kaplanMeier,logRankTest}from'../src/core/stats.js';
test('descriptive statistics are stable',()=>{assert.equal(mean([1,2,3,4]),2.5);assert.equal(variance([1,2,3,4]),1.6666666666666667);const summary=descriptiveSummary([1,2,3,4]);assert.equal(summary.median,2.5);assert.equal(summary.q1,1.75);assert.equal(summary.q3,3.25);assert.ok(summary.sem>0);assert.equal(summary.confidenceInterval95.length,2)});
test('Student-t quantiles and intervals use finite-sample critical values',()=>{assert.ok(Math.abs(studentTQuantile(.975,9)-2.262157)<1e-4);const result=welchTTest([1,2,3],[5,6,7]);assert.ok(result.criticalValue95>2);assert.ok(result.confidenceInterval95[0]<result.difference&&result.confidenceInterval95[1]>result.difference)});
test('Welch test detects a strong difference',()=>{const r=welchTTest([92,88,95,90,87,93],[70,74,69,76,72,68]);assert.ok(r.difference>19);assert.ok(r.pValue<.001);assert.equal(r.method,'Welch two-sample t-test')});
test('Student test reports pooled variance, effect size, and pooled degrees of freedom',()=>{const r=studentTTest([1,2,3,4],[5,6,7,8]);assert.equal(r.df,6);assert.equal(r.pooledVariance,1.6666666666666667);assert.ok(r.effectSizeCohensD< -2);assert.ok(r.pValue<.01);assert.equal(r.method,'Student two-sample t-test')});
test('two-way ANOVA separates factor and interaction effects',()=>{const rows=[];for(const a of ['Control','Treatment'])for(const b of ['WT','KO'])for(let i=0;i<3;i++)rows.push({a,b,value:(a==='Treatment'?5:0)+(b==='KO'?3:0)+i*.1});const r=twoWayAnova(rows,'a','b','value');assert.equal(r.dfInteraction,1);assert.ok(r.pA<.001);assert.ok(r.pB<.001);assert.equal(r.n,12)})
test('one-way ANOVA detects separated means',()=>{const r=oneWayAnova([[1,2,3],[5,6,7],[9,10,11]]);assert.ok(r.f>40);assert.ok(r.pValue<.001)});
test('paired and rank tests return reproducible inferential results',()=>{const paired=pairedTTest([10,12,11,13,12],[12,15,13,16,14]);assert.equal(paired.n,5);assert.ok(paired.pValue<.01);const rank=mannWhitney([1,2,3,4],[8,9,10,11]);assert.ok(rank.pValue<.05);assert.equal(rank.method,'Mann–Whitney U test')});
test('Spearman and Wilcoxon procedures handle rank-based workflows',()=>{const correlation=spearmanCorrelation([1,2,3,4,5],[10,8,7,3,1]);assert.ok(correlation.rho<-.9);const result=wilcoxonSignedRank([10,12,14,16,18],[8,10,11,12,13]);assert.equal(result.n,5);assert.ok(result.pValue<.05);assert.equal(result.method,'Wilcoxon signed-rank test')});
test('correlation and regression recover a linear relationship',()=>{const correlation=pearsonCorrelation([1,2,3,4,5],[2,4,6,8,10]);assert.ok(correlation.r>.99);const regression=linearRegression([1,2,3,4,5],[2,4,6,8,10]);assert.equal(regression.slope,2);assert.equal(regression.intercept,0);assert.equal(regression.r2,1);assert.deepEqual(regression.residuals,[0,0,0,0,0]);assert.equal(regression.rmse,0)});
test('Holm correction preserves monotonic adjusted p-values',()=>{const p=holmAdjust([.001,.02,.5]);assert.ok(p[0]<=p[1]);assert.ok(p[1]<=p[2]);assert.ok(p[0]>=.003)});
test('pairwise comparisons attach selectable multiplicity corrections',()=>{const r=pairwiseWelch([[1,2,3],[5,6,7],[9,10,11]],['A','B','C']);assert.equal(r.length,3);assert.equal(r[0].correction,'Holm');assert.ok(r.every(x=>x.adjustedPValue>=x.pValue));const bh=pairwiseWelch([[1,2,3],[5,6,7],[9,10,11]],['A','B','C'],'Benjamini–Hochberg');assert.equal(bh[0].correction,'Benjamini–Hochberg')});
test('nonparametric, contingency, and FDR procedures return validated results',()=>{const kw=kruskalWallis([[1,2,3],[4,5,6],[8,9,10]]);assert.equal(kw.df,2);assert.ok(kw.pValue<.05);const chi=chiSquareTest([[20,5],[4,21]]);assert.equal(chi.df,1);assert.ok(chi.pValue<.001);const adjusted=benjaminiHochberg([.001,.02,.5]);assert.ok(adjusted[0]<=adjusted[1]);assert.ok(adjusted[2]<=1)})
test('Fisher exact test handles sparse 2 × 2 tables',()=>{const result=fisherExactTest([[8,1],[1,8]]);assert.ok(result.oddsRatio>20);assert.ok(result.pValue<.01);assert.equal(result.n,18)})
test('survival estimators preserve event and risk-set accounting',()=>{const km=kaplanMeier([1,2,3,4,5],[1,0,1,1,0]);assert.equal(km.events,3);assert.equal(km.censored,2);assert.ok(Math.abs(km.curve.at(-1).survival-0.2666666667)<1e-9);const lr=logRankTest([1,2,3,4],[1,1,1,1],[1,2,3,4],[0,0,0,0]);assert.equal(lr.df,1);assert.ok(lr.statistic>0)})
test('Friedman test handles matched repeated measurements',()=>{const result=friedmanTest([[1,2,3,4],[2,3,4,5],[6,7,8,9]]);assert.equal(result.conditions,3);assert.equal(result.n,4);assert.ok(result.pValue<.05);assert.equal(result.rankSums.length,3)})
test('four-parameter logistic fitting recovers a dose response',()=>{const result=fitFourParameterLogistic([1,2,4,8,16],[77.25715247,65.7384364,50,34.2615636,22.74284753]);assert.ok(result.ec50>3&&result.ec50<5);assert.ok(result.r2>.999);assert.ok(result.hillSlope>.8&&result.hillSlope<1.6)})
