import {
  type Analysis,
  type DataTable,
  type Project,
  APP_VERSION,
  analysisColumns,
  formatP,
  methodInfo,
  methodsSentence,
  runAnalysis,
  significanceStars,
} from './model.ts';

export interface TableDigest {
  id: string;
  name: string;
  shape: string;
  columns: string[];
  rows: number;
  values: number;
  sha256: string;
}

export interface Report {
  project: string;
  generatedAt: string;
  engine: string;
  tables: TableDigest[];
  analyses: {
    name: string;
    table: string;
    method: string;
    columns: string[];
    options: Record<string, unknown>;
    summary: { label: string; value: string; note?: string }[];
    comparisons: { pair: string; raw: string; adjusted: string; stars: string }[];
    warnings: string[];
    error: string | null;
    sentence: string;
  }[];
  figures: { name: string; table: string; plot: string; boundTo: string | null }[];
}

/**
 * Canonical text for a table: column names, then every cell, tab separated.
 * Blanks and text go in literally, so a stray "N/A" changes the digest too.
 */
function canonicalise(table: DataTable): string {
  const header = table.columns.map((column) => `${column.name}\u0000${column.role}`).join('\t');
  const body = table.rows
    .map((row) => table.columns.map((_, index) => {
      const cell = row[index];
      return cell === null || cell === undefined ? '' : String(cell);
    }).join('\t'))
    .join('\n');
  return `${table.shape}\n${header}\n${body}`;
}

async function sha256(text: string): Promise<string> {
  const bytes = new TextEncoder().encode(text);
  const digest = await crypto.subtle.digest('SHA-256', bytes);
  return [...new Uint8Array(digest)].map((byte) => byte.toString(16).padStart(2, '0')).join('');
}

export async function digestTable(table: DataTable): Promise<TableDigest> {
  const numeric = table.rows.reduce(
    (count, row) => count + row.filter((cell) => typeof cell === 'number' && Number.isFinite(cell)).length,
    0
  );
  return {
    id: table.id,
    name: table.name,
    shape: table.shape,
    columns: table.columns.map((column) => column.name),
    rows: table.rows.length,
    values: numeric,
    sha256: await sha256(canonicalise(table)),
  };
}

function describeOptions(analysis: Analysis): Record<string, unknown> {
  const { columnIds, ...rest } = analysis.options;
  return rest;
}

export async function buildReport(project: Project): Promise<Report> {
  const tables = await Promise.all(project.tables.map(digestTable));
  const nameOf = (id: string) => project.tables.find((table) => table.id === id)?.name ?? 'missing table';

  const analyses = project.analyses.map((analysis) => {
    const table = project.tables.find((entry) => entry.id === analysis.tableId);
    if (!table) {
      return {
        name: analysis.name, table: 'missing table', method: methodInfo(analysis.method).label,
        columns: [], options: {}, summary: [], comparisons: [], warnings: [],
        error: 'The data table this analysis was built on has been deleted.', sentence: '',
      };
    }
    const result = runAnalysis(table, analysis);
    return {
      name: analysis.name,
      table: table.name,
      method: result.method || methodInfo(analysis.method).label,
      columns: analysisColumns(table, analysis).map((column) => column.name),
      options: describeOptions(analysis),
      summary: result.summary,
      comparisons: result.comparisons.map((comparison) => ({
        pair: `${comparison.labelA} vs ${comparison.labelB}`,
        raw: formatP(comparison.pValue),
        adjusted: formatP(comparison.pAdjusted),
        stars: significanceStars(comparison.pAdjusted),
      })),
      warnings: result.warnings,
      error: result.error,
      sentence: methodsSentence(table, analysis, result),
    };
  });

  return {
    project: project.name,
    generatedAt: new Date().toISOString(),
    engine: `AssayPlot ${APP_VERSION}`,
    tables,
    analyses,
    figures: project.figures.map((figure) => ({
      name: figure.name,
      table: nameOf(figure.tableId),
      plot: figure.plotType,
      boundTo: project.analyses.find((entry) => entry.id === figure.analysisId)?.name ?? null,
    })),
  };
}

export function reportToMarkdown(report: Report): string {
  const out: string[] = [];
  out.push(`# ${report.project}`);
  out.push('');
  out.push(`Analysis report generated by ${report.engine} on ${report.generatedAt.slice(0, 10)}.`);
  out.push('');
  out.push('Each data table below carries a SHA-256 of its contents. Recomputing the');
  out.push('digest from the same data reproduces the same value, so a reviewer can');
  out.push('confirm that the numbers analysed are the numbers supplied.');
  out.push('');

  out.push('## Data');
  out.push('');
  for (const table of report.tables) {
    out.push(`### ${table.name}`);
    out.push('');
    out.push(`- Shape: ${table.shape}`);
    out.push(`- Columns: ${table.columns.join(', ')}`);
    out.push(`- ${table.rows} rows, ${table.values} numeric values`);
    out.push(`- SHA-256: \`${table.sha256}\``);
    out.push('');
  }

  out.push('## Analyses');
  out.push('');
  if (!report.analyses.length) out.push('_No analyses in this project._');
  for (const analysis of report.analyses) {
    out.push(`### ${analysis.name}`);
    out.push('');
    out.push(`- Method: ${analysis.method}`);
    out.push(`- Data: ${analysis.table}`);
    out.push(`- Columns used: ${analysis.columns.join(', ') || '—'}`);
    for (const [key, value] of Object.entries(analysis.options)) {
      out.push(`- ${key}: ${String(value)}`);
    }
    out.push('');

    if (analysis.error) {
      out.push(`**This analysis did not run.** ${analysis.error}`);
      out.push('');
      continue;
    }

    if (analysis.summary.length) {
      out.push('| Quantity | Value | Note |');
      out.push('|---|---|---|');
      for (const entry of analysis.summary) {
        out.push(`| ${entry.label} | ${entry.value} | ${entry.note ?? ''} |`);
      }
      out.push('');
    }

    if (analysis.comparisons.length > 1) {
      out.push('| Comparison | P (raw) | P (adjusted) | |');
      out.push('|---|---|---|---|');
      for (const comparison of analysis.comparisons) {
        out.push(`| ${comparison.pair} | ${comparison.raw} | ${comparison.adjusted} | ${comparison.stars} |`);
      }
      out.push('');
    }

    for (const warning of analysis.warnings) {
      out.push(`> ${warning}`);
      out.push('');
    }

    if (analysis.sentence) {
      out.push('**Methods**');
      out.push('');
      out.push(analysis.sentence);
      out.push('');
    }
  }

  if (report.figures.length) {
    out.push('## Figures');
    out.push('');
    out.push('| Figure | Plot | Data | Significance from |');
    out.push('|---|---|---|---|');
    for (const figure of report.figures) {
      out.push(`| ${figure.name} | ${figure.plot} | ${figure.table} | ${figure.boundTo ?? '—'} |`);
    }
    out.push('');
  }

  out.push('---');
  out.push('');
  out.push(`Produced by ${report.engine}. Not validated for clinical or regulatory use.`);
  return out.join('\n');
}

const escapeHtml = (text: string) =>
  text.replace(/[&<>"]/g, (character) =>
    ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[character] as string));

/** A self-contained page, so it can be opened, printed, or pasted anywhere. */
export function reportToHtml(report: Report): string {
  const markdown = reportToMarkdown(report);
  const body = markdown
    .split('\n')
    .map((line) => {
      if (line.startsWith('### ')) return `<h3>${escapeHtml(line.slice(4))}</h3>`;
      if (line.startsWith('## ')) return `<h2>${escapeHtml(line.slice(3))}</h2>`;
      if (line.startsWith('# ')) return `<h1>${escapeHtml(line.slice(2))}</h1>`;
      if (line.startsWith('> ')) return `<p class="warn">${escapeHtml(line.slice(2))}</p>`;
      if (line.startsWith('- ')) return `<li>${escapeHtml(line.slice(2))}</li>`;
      if (line.startsWith('|')) return `ROW${line}`;
      if (line === '---') return '<hr>';
      if (!line.trim()) return '';
      return `<p>${escapeHtml(line)}</p>`;
    })
    .join('\n');

  // Fold the marked-up table rows into real tables.
  const withTables = body.replace(/(?:^ROW\|.*$\n?)+/gm, (block) => {
    const rows = block.trim().split('\n').map((line) => line.replace(/^ROW/, ''));
    const cells = rows
      .filter((row) => !/^\|[\s|:-]+\|$/.test(row))
      .map((row) => row.split('|').slice(1, -1).map((cell) => cell.trim()));
    if (!cells.length) return '';
    const [header, ...rest] = cells;
    return [
      '<table><thead><tr>',
      header.map((cell) => `<th>${escapeHtml(cell)}</th>`).join(''),
      '</tr></thead><tbody>',
      rest.map((row) => `<tr>${row.map((cell) => `<td>${escapeHtml(cell)}</td>`).join('')}</tr>`).join(''),
      '</tbody></table>',
    ].join('');
  }).replace(/(?:^<li>.*<\/li>$\n?)+/gm, (block) => `<ul>${block.trim()}</ul>`);

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>${escapeHtml(report.project)} — analysis report</title>
<style>
  body { max-width: 46rem; margin: 3rem auto; padding: 0 1.5rem;
         font: 15px/1.6 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
         color: #131d1c; }
  h1 { font-size: 1.8rem; margin-bottom: 0.3rem; }
  h2 { font-size: 1.25rem; margin-top: 2.2rem; padding-bottom: 0.3rem;
       border-bottom: 1px solid #dde4e2; }
  h3 { font-size: 1.02rem; margin-top: 1.6rem; }
  table { border-collapse: collapse; width: 100%; margin: 0.8rem 0; font-size: 0.92rem; }
  th, td { text-align: left; padding: 6px 10px; border-bottom: 1px solid #dde4e2; }
  th { font-weight: 600; background: #eef2f1; }
  ul { padding-left: 1.2rem; }
  code { background: #eef2f1; padding: 1px 4px; border-radius: 3px;
         font: 0.86em ui-monospace, Menlo, monospace; word-break: break-all; }
  .warn { background: #fbf1dd; border-left: 3px solid #c8952f; padding: 0.6rem 0.8rem;
          margin: 0.8rem 0; }
  hr { border: none; border-top: 1px solid #dde4e2; margin: 2.5rem 0 1rem; }
  @media print { body { margin: 0; max-width: none; } }
</style>
</head>
<body>
${withTables.replace(/`([^`]+)`/g, '<code>$1</code>')}
</body>
</html>`;
}
