const p = value => Number.isFinite(value) ? (value < 0.001 ? '< 0.001' : value.toFixed(3)) : 'not available';

export function methodsSummary({method='descriptive', result={}, groups=[], xKey, yKey, correction='Holm'}={}) {
  if (method === 'welch') return `A Welch two-sample t-test compared ${groups[0] || 'group 1'} with ${groups[1] || 'group 2'} (n = ${result.nA ?? '—'} and ${result.nB ?? '—'}). The estimated difference in means was ${result.difference?.toFixed?.(2) ?? '—'}; 95% CI ${result.confidenceInterval95?.map(v => v.toFixed(2)).join(' to ') ?? '—'}, Cohen’s d = ${result.effectSizeCohensD?.toFixed?.(2) ?? '—'}, t(${result.df?.toFixed?.(2) ?? '—'}) = ${result.t?.toFixed?.(2) ?? '—'}, p ${p(result.pValue)}.`;
  if (method === 'student') return `A pooled-variance Student two-sample t-test compared ${groups[0] || 'group 1'} with ${groups[1] || 'group 2'} (n = ${result.nA ?? '—'} and ${result.nB ?? '—'}), assuming equal variances. The estimated difference in means was ${result.difference?.toFixed?.(2) ?? '—'}, Cohen’s d = ${result.effectSizeCohensD?.toFixed?.(2) ?? '—'}, t(${result.df ?? '—'}) = ${result.t?.toFixed?.(2) ?? '—'}, p ${p(result.pValue)}.`;
  if (method === 'mannwhitney') return `A two-sided Mann–Whitney U test compared ${groups[0] || 'group 1'} with ${groups[1] || 'group 2'} (n = ${result.nA ?? '—'} and ${result.nB ?? '—'}). The test statistic was U = ${result.u?.toFixed?.(2) ?? '—'}, z = ${result.z?.toFixed?.(2) ?? '—'}, p ${p(result.pValue)}.`;
  if (method === 'paired') return `A paired t-test compared ${xKey || 'measurement 1'} with ${yKey || 'measurement 2'} across ${result.n ?? '—'} matched observations. The mean paired change (first − second) was ${result.meanDifference?.toFixed?.(2) ?? '—'}; 95% CI ${result.confidenceInterval95?.map(v => v.toFixed(2)).join(' to ') ?? '—'}, t(${result.df ?? '—'}) = ${result.t?.toFixed?.(2) ?? '—'}, p ${p(result.pValue)}.`;
  if (method === 'wilcoxon') return `A Wilcoxon signed-rank test compared ${xKey || 'measurement 1'} with ${yKey || 'measurement 2'} across ${result.n ?? '—'} non-zero matched differences. The median paired change was ${result.medianDifference?.toFixed?.(2) ?? '—'}, W = ${result.w?.toFixed?.(2) ?? '—'}, p ${p(result.pValue)}.`;
  if (method === 'anova') return `A one-way analysis of variance compared ${groups.length || 'multiple'} groups (N = ${result.n ?? '—'}). The result was F(${result.dfBetween ?? '—'}, ${result.dfWithin ?? '—'}) = ${result.f?.toFixed?.(2) ?? '—'}, p ${p(result.pValue)}. Pairwise follow-up comparisons used ${correction}-adjusted Welch tests.`;
  if (method === 'two-way') return `A balanced two-way analysis of variance assessed two main effects and their interaction (N = ${result.n ?? '—'}). Factor A: F(${result.dfA ?? '—'}, ${result.dfError ?? '—'}) = ${result.fA?.toFixed?.(2) ?? '—'}, p ${p(result.pA)}; factor B: F(${result.dfB ?? '—'}, ${result.dfError ?? '—'}) = ${result.fB?.toFixed?.(2) ?? '—'}, p ${p(result.pB)}; interaction p ${p(result.pInteraction)}.`;
  if (method === 'chi-square') return `A Pearson chi-square test assessed the association between group and ${result.outcome || 'the categorical outcome'} (N = ${result.n ?? '—'}). The result was χ²(${result.df ?? '—'}) = ${result.statistic?.toFixed?.(2) ?? '—'}, p ${p(result.pValue)}.`;
  if (method === 'fisher') return `Fisher’s exact test assessed the association between ${result.outcome || 'the categorical outcome'} and group in a 2 × 2 table (N = ${result.n ?? '—'}). The odds ratio was ${result.oddsRatio?.toFixed?.(2) ?? '—'}, p ${p(result.pValue)}.`;
  if (method === 'survival') return `Kaplan–Meier survival curves were estimated using ${result.timeKey || 'follow-up time'} and ${result.eventKey || 'event status'}. Survival distributions were compared between two groups using a two-sided log-rank test (χ²(${result.df ?? '—'}) = ${result.statistic?.toFixed?.(2) ?? '—'}, p ${p(result.pValue)}).`;
  if (method === 'friedman') return `A Friedman test compared ${result.conditions ?? 'multiple'} matched conditions across ${result.n ?? '—'} complete observations (χ²(${result.df ?? '—'}) = ${result.statistic?.toFixed?.(2) ?? '—'}, p ${p(result.pValue)}).`;
  if (method === 'correlation') return `A Pearson correlation assessed the linear association between ${xKey || 'the predictor'} and ${yKey || 'the outcome'} across ${result.n ?? '—'} paired observations (r = ${result.r?.toFixed?.(3) ?? '—'}, t(${result.df ?? '—'}) = ${result.t?.toFixed?.(2) ?? '—'}, p ${p(result.pValue)}).`;
  if (method === 'spearman') return `A Spearman rank correlation assessed the monotonic association between ${xKey || 'the predictor'} and ${yKey || 'the outcome'} across ${result.n ?? '—'} paired observations (ρ = ${result.rho?.toFixed?.(3) ?? '—'}, p ${p(result.pValue)}).`;
  if (method === 'regression') return `A simple linear regression modeled ${yKey || 'the outcome'} from ${xKey || 'the predictor'} across ${result.n ?? '—'} paired observations. The slope was ${result.slope?.toFixed?.(3) ?? '—'} (intercept ${result.intercept?.toFixed?.(3) ?? '—'}, R² = ${result.r2?.toFixed?.(3) ?? '—'}).`;
  return 'Descriptive statistics were calculated for the imported observations. No inferential test was selected.';
}
